name: "2. Usecase"

on:
  push:
    branches:
      - main
  gollum:

jobs:
  check_mockup_uc_wiki:
    name: 'Проверка наличия вики-страницы "Макет и сценарий использования" и разделов "Макет UI" "Сценарий использования" в ней'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: Check wiki
        with:
          repository: ${{github.repository}}.wiki
      - name: check
        run: bash .github/workflows/scripts/2_usecase.sh
