name: "3. Модель данных"

on:
  push:
    branches:
      - main
  gollum:

jobs:
  check_data_model:
    name: 'Проверка наличия вики-страницы "Модель данных" и разделов "Нереляционная модель",  "Реляционная модель", "Сравнение моделей", "Вывод" в ней'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: Check wiki
        with:
          repository: ${{github.repository}}.wiki
      - name: check
        run: bash .github/workflows/scripts/3_data_model.sh
